### ISSUE TITLE
exec_request: missing second parameter

### ISSUE THREAD

**Issue by medfelis** [pdfcrowd/pdfcrowd-php#10]
The method exec_request is also used with only one parameter:
https://github.com/pdfcrowd/pdfcrowd-php/blob/64b882acce5a8e3ba4cd722848d7d39cb94eca4e/pdfcrowd.php#L676

Suggestion:
Add default value NULL for second parameter:
`private function exec_request($c, $out_stream = null)`

https://github.com/pdfcrowd/pdfcrowd-php/blob/64b882acce5a8e3ba4cd722848d7d39cb94eca4e/pdfcrowd.php#L741

**Comment by foxmadr** [comment]
The 2nd parameter was removed as unused.

**Comment by medfelis** [comment]
THX for the hyper-fast adjustment!
