### ISSUE TITLE
Any breaking changes in v5?

### ISSUE THREAD

**Issue by Mark-H** [pdfcrowd/pdfcrowd-php#13]
Still using v4.7 of the client, and just wondering if there are any breaking changes to be on the lookout for. 

[The diff between 4.7 and 5.1 is huge](https://github.com/pdfcrowd/pdfcrowd-php/compare/4.7.0...5.1.0) so just wondering if there's a recent changelog or something to help with updating the integration.

**Comment by pdfcrowd** [comment]
The 5.x API client is almost fully backward compatible and upgrade from 4.x should be smooth. The main difference is that 5.x uses a newer rendering engine which should produce more accurate output.

The only API integration breaking change is that `setDisableSmartShrinking(true)`  was replaced with `setSmartScalingMode('mode1')`. Other than that, no changes are required.

If you for some reason don't like the output from the new engine, you can switch to the one used in 4.x with `setConverterVersion("18.10")`.

A short summary of the new version features can be found here: [https://pdfcrowd.com/blog/new-converter-version-20.10-released/](https://pdfcrowd.com/blog/new-converter-version-20.10-released/)

**Comment by Mark-H** [comment]
Thanks for responding so quickly - only just got around to working on the upgrade again, but it seems to work as expected.
