### ISSUE TITLE
Undefined variable $use_curl

### ISSUE THREAD

**Issue by Mark-H** [pdfcrowd/pdfcrowd-php#14]
```
    function setUseCurl($value) {
        $this->helper->setUseCurl($use_curl);
        return $this;
    }
```

I'm not using the code, but `$use_curl` should be `$value` for that to work. 

Is repeated 5 times (line 2741, 3624, 4061, 4649, 5072).

**Comment by foxmadr** [comment]
Mark, thank you. It is fixed now.
