### ISSUE TITLE
Convert to Composer Package

### ISSUE THREAD

**Issue by davidkryzaniak** [pdfcrowd/pdfcrowd-php#4]
"Copy pdfcrowd.php to your source directory" What?! 

![alt text](http://lovelace-media.imgix.net/uploads/360/bd0525e0-4d18-0133-6d39-0aecee5a8273.gif)

It would be pretty neat if this was a composer package.

**Comment by foxmadr** [comment]
Solved, try to use:
`$ composer require pdfcrowd/pdfcrowd`
