### ISSUE TITLE
Error code list

### ISSUE THREAD

**Issue by sajumani** [pdfcrowd/pdfcrowd-php#5]
Hi,

Can i get the possible errors and this code ??.it should support for development..

**Comment by foxmadr** [comment]
For the new API use:
[https://pdfcrowd.com/doc/api/status-codes/](https://pdfcrowd.com/doc/api/status-codes/)
For the original API use Return Codes section in:
[https://pdfcrowd.com/html-to-pdf-api](https://pdfcrowd.com/html-to-pdf-api)
