### ISSUE TITLE
Not able to write pdf to file

### ISSUE THREAD

**Issue by KomalDivate** [pdfcrowd/pdfcrowd-php#7]
I'm working on laravel framework and want to convert html to pdf using pdfcrowd. It created a blank pdf file. But not able to write data to it. Please help me as soon as possible. Below is the code snippet.

$out_file = fopen('pdf/file.pdf', "wb");
$pdf = $client->convertFile($html_mail,$out_file);
fclose($out_file);

**Comment by foxmadr** [comment]
Please try to use the new API. Here is the sample:
[https://pdfcrowd.com/doc/api/html-to-pdf/php/#examples-file-to-pdf](https://pdfcrowd.com/doc/api/html-to-pdf/php/#examples-file-to-pdf)

**Comment by andela-araimi** [comment]
I am having the same issue then came across this; I tried most of the examples given in that link; I got empty pdf file, didn't write successfully. Any idea?

**Comment by foxmadr** [comment]
Which URL are you trying to convert?

**Comment by andela-araimi** [comment]
"https://www.punjabmedicalcouncil.com/receipt_form.php?app=permambbspass&payment_id=MOJO8123005N88286846&payment_request_id=64d6ec2341f44463a50d06554cd80194"

It works online and also when I use the download code, but it doesn't just write to file

**Comment by foxmadr** [comment]
Are you getting some error?
Could you send us a sample implementation to support@pdfcrowd.com?

**Comment by foxmadr** [comment]
closed due to long inactivity and missing data for replication
