### ISSUE TITLE
Error notice with beta API: incorrect value for CURLOPT_SSL_VERIFYHOST

### ISSUE THREAD

**Issue by croxton** [pdfcrowd/pdfcrowd-php#9]
Line 629 of `pdfcrowd.php` causes an error notice when using the new beta API:

    curl_setopt($c, CURLOPT_SSL_VERIFYHOST, true);

I receive the following error notice:

    curl_setopt(): CURLOPT_SSL_VERIFYHOST no longer accepts the value 1, value 2 will be used instead

Changing line 629 as follows fixes the issue:

    curl_setopt($c, CURLOPT_SSL_VERIFYHOST, 2);

Tested with PHP 7.

**Comment by foxmadr** [comment]
Solved by applying:
`curl_setopt($c, CURLOPT_SSL_VERIFYHOST, 2);`
